<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ricardo Pérez Castillo">
<meta name="dcterms.date" content="2026-08-17">
<meta name="description" content="Pixel-level cloud classification on NASA MISR imagery, where clouds and sea ice are equally bright and equally cold. 0.996 AUC on the held-out orbit, 0.89 on a different one — and why that gap is the real result.">

<title>Cloud or Ice: Arctic Cloud Detection from Multi-Angle Satellite Imagery – Ricardo Pérez Castillo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<link href="../../favicon.svg" rel="icon" type="image/svg+xml">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea1d7ac60288e0f1efdbc993fd8432ae.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ERRXK3H3TZ"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-ERRXK3H3TZ', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"simple",
  "consent_type":"express",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  ,
"language":"en"
  });
});
</script> 
  
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;family=Newsreader:opsz,wght@6..72,500;6..72,600&amp;display=swap" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Cloud or Ice: Arctic Cloud Detection from Multi-Angle Satellite Imagery – Ricardo Pérez Castillo">
<meta property="og:description" content="Pixel-level cloud classification on NASA MISR imagery, where clouds and sea ice are equally bright and equally cold. 0.996 AUC on the held-out orbit, 0.89 on a different one — and why that gap is the real result.">
<meta property="og:image" content="https://ricardo-pc.github.io/posts/arctic-cloud-detection/spatial_errors.png">
<meta property="og:site_name" content="Ricardo Pérez Castillo">
<meta property="og:image:height" content="1020">
<meta property="og:image:width" content="1360">
<meta name="twitter:title" content="Cloud or Ice: Arctic Cloud Detection from Multi-Angle Satellite Imagery – Ricardo Pérez Castillo">
<meta name="twitter:description" content="Pixel-level cloud classification on NASA MISR imagery, where clouds and sea ice are equally bright and equally cold. 0.996 AUC on the held-out orbit, 0.89 on a different one — and why that gap is the real result.">
<meta name="twitter:image" content="https://ricardo-pc.github.io/posts/arctic-cloud-detection/spatial_errors.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="1020">
<meta name="twitter:image-width" content="1360">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ricardo Pérez Castillo</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Work</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../index.html#about"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ricardo-pc"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ricardoperezcastillo/"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:ricardoperez@berkeley.edu"> <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link active" data-scroll-target="#the-problem">The Problem</a></li>
  <li><a href="#the-data" id="toc-the-data" class="nav-link" data-scroll-target="#the-data">The Data</a></li>
  <li><a href="#before-any-model-auditing-the-data" id="toc-before-any-model-auditing-the-data" class="nav-link" data-scroll-target="#before-any-model-auditing-the-data">Before Any Model: Auditing the Data</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering">Feature Engineering</a></li>
  <li><a href="#transfer-learning-an-autoencoder-on-unlabeled-patches" id="toc-transfer-learning-an-autoencoder-on-unlabeled-patches" class="nav-link" data-scroll-target="#transfer-learning-an-autoencoder-on-unlabeled-patches">Transfer Learning: An Autoencoder on Unlabeled Patches</a></li>
  <li><a href="#why-a-random-split-would-have-been-a-lie" id="toc-why-a-random-split-would-have-been-a-lie" class="nav-link" data-scroll-target="#why-a-random-split-would-have-been-a-lie">Why a Random Split Would Have Been a Lie</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#technologies-tools" id="toc-technologies-tools" class="nav-link" data-scroll-target="#technologies-tools">Technologies &amp; Tools</a></li>
  <li><a href="#links-resources" id="toc-links-resources" class="nav-link" data-scroll-target="#links-resources">Links &amp; Resources</a></li>
  <li><a href="#reflection" id="toc-reflection" class="nav-link" data-scroll-target="#reflection">Reflection</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cloud or Ice: Arctic Cloud Detection from Multi-Angle Satellite Imagery</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning</div>
    <div class="quarto-category">Remote Sensing</div>
    <div class="quarto-category">Data Engineering</div>
  </div>
  </div>

<div>
  <div class="description">
    Pixel-level cloud classification on NASA MISR imagery, where clouds and sea ice are equally bright and equally cold. 0.996 AUC on the held-out orbit, 0.89 on a different one — and why that gap is the real result.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ricardo Pérez Castillo </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Project Overview
</div>
</div>
<div class="callout-body-container callout-body">
<p>A pixel-level cloud detector trained on NASA MISR multi-angle satellite imagery of the Arctic, where standard brightness-based cloud detection fails because snow-covered ice is just as bright and just as cold as a cloud top. The headline model scores 0.9958 AUC on its held-out test image — rotate which of the three available images gets held out instead, and the same model scores as low as 0.8874. That gap, not the leaderboard, is the real finding.</p>
<p>Course: STAT 214: Data Analysis and Machine Learning for Real-World Decision Making · Semester: Spring 2026 · Language: Python</p>
<p><strong><a href="https://ricardo-pc.github.io/arctic-cloud-detection/">▶ Explore the interactive version</a></strong>: play cloud detector against the real trained model, inspect any of 115,032 real pixels on a live raster map, drag a threshold across real feature distributions, and see exactly where — and why — the model gets it wrong.</p>
<p><a href="https://github.com/ricardo-pc/stat-214/tree/main/lab2">GitHub Repository</a></p>
</div>
</div>
<section id="the-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-problem">The Problem</h2>
<p>Most cloud-detection algorithms lean on a simple rule: clouds are bright, the ground underneath usually isn’t. That rule collapses in the Arctic. Snow and sea ice are just as reflective and just as cold as cloud tops, so a brightness threshold that works over open ocean or temperate land is close to useless here — exactly the problem NASA’s Multi-angle Imaging SpectroRadiometer (MISR) was built to solve.</p>
<p>MISR photographs the same 275-metre patch of ground from five camera angles within minutes of each other: DF (70.5°), CF (60°), BF (45.6°), AF (26.1°), and AN, looking straight down (0°). The physics is the signal: cloud tops scatter light strongly forward, so the DF camera sees them as much brighter than the AN camera does. Flat ice and snow scatter close to uniformly across angles. The difference between camera angles carries the classification signal that raw brightness cannot.</p>
</section>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>Three labeled MISR orbits over the same Arctic region (path 26, 2002 daylight season), spanning a full seasonal transition — late April through mid June — plus 161 additional unlabeled orbits available for unsupervised pre-training.</p>
<ul>
<li>~345,000 total pixels; 207,681 carry expert cloud/not-cloud labels</li>
<li>Training set: O012791 + O013257 (125,598 labeled pixels, 33.2% cloud)</li>
<li>Test set: O013490, held out by date (82,083 labeled pixels, 47.8% cloud — real seasonal drift as the melt season progresses)</li>
<li>Eight raw/engineered features per pixel going into the final model: the five radiances, SD (local texture), CORR (cross-angle correlation), and NDAI_DF_AF (an angular scattering ratio)</li>
</ul>
</section>
<section id="before-any-model-auditing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="before-any-model-auditing-the-data">Before Any Model: Auditing the Data</h2>
<p>Every accuracy number in this project rests on two things I checked before training anything.</p>
<p><strong>Outlier detection.</strong> A 3σ rule across all eight features flags 21,609 pixels (6.3%) across the three orbits. The reflex is to drop them. Instead I checked where they were — they weren’t scattered randomly, they clustered on one specific coastline. That’s Greenland’s edge, a region with known poor cross-angle terrain registration at sharp elevation changes (Shi et al.&nbsp;2008). Real sensor-geometry artifact, not noise. Retained and flagged, not dropped.</p>
<p><strong>The label buffer.</strong> This is the finding that isn’t in our submitted report. Across all three labeled orbits, every single pair of side-by-side labeled pixels shares the same label — 161,367 adjacent pairs in the test orbit, 139,631 and 107,028 in the two training orbits, zero disagreements anywhere. That’s not a fact about clouds; it’s a property of how the labels were drawn. Experts assigned regions, not individual pixels, and left an unlabeled buffer around every class transition — an empirical minimum of 6.0 grid units between opposite-class labels, against a theoretical grid spacing of 1.0.</p>
<p>The consequence: the labeled test set structurally excludes the pixels the model finds hardest. Every accuracy number in this project — and probably in the source literature — is computed on the easy pixels.</p>
</section>
<section id="feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h2>
<p>Eight features, ranked by separability (AUC / KS statistic / mutual information, computed independently so no single metric’s blind spot could inflate a feature’s apparent value):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>AUC</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SD</td>
<td>0.935</td>
<td>Local texture. Cloud pixels average 4.4× the SD of not-cloud pixels.</td>
</tr>
<tr class="even">
<td>NDAI (textbook)</td>
<td>0.823</td>
<td>(DF−AN)/(DF+AN)</td>
</tr>
<tr class="odd">
<td>AF</td>
<td>0.799</td>
<td>Strongest single raw radiance angle</td>
</tr>
<tr class="even">
<td>CORR</td>
<td>0.524</td>
<td>Barely better than chance — see below</td>
</tr>
</tbody>
</table>
<p>CORR — one of three pillars of the original Shi et al.&nbsp;labeling rule — is nearly useless alone on this data (AUC 0.524). It’s built to catch high-altitude clouds, where cross-angle registration shift is large; these three orbits are dominated by low-altitude cloud that looks nearly identical from every angle. Kept in the final feature set anyway, since a tree-based model can use it in combination even when it contributes almost nothing alone — and permutation importance later confirms it does (0.0196), unlike the raw DF radiance, which goes measurably negative.</p>
<p>I also swept six ways of building an angular scattering ratio, (a−b)/(a+b), across every camera pair. <code>NDAI_DF_AF</code> (comparing DF to AF instead of AN) beat the textbook version on all three metrics and is what the selected model uses. <code>NDAI_AF_AN</code> landed at exactly 0.500 AUC — chance — because AF and AN are only 26° apart, not enough angular separation to carry any signal. A clean negative result, and useful for the same reason a positive one is.</p>
</section>
<section id="transfer-learning-an-autoencoder-on-unlabeled-patches" class="level2">
<h2 class="anchored" data-anchor-id="transfer-learning-an-autoencoder-on-unlabeled-patches">Transfer Learning: An Autoencoder on Unlabeled Patches</h2>
<p>Hand-built features are defined at a single pixel; cloud is a spatially coherent thing. With 161 unlabeled orbits sitting unused, I trained a convolutional autoencoder on 9×9×8 patches (648 dims → 32-dim embedding → 648 reconstruction, MSE loss) to learn spatial texture without any labels, then fused the 32 embeddings with the eight hand-built features.</p>
<p>The honest result: it didn’t help. Random Forest actually got worse with the embeddings added (AUC 0.9944 on 3 features down to 0.9861 on 40). HGB gained +0.0001 (0.9958 → 0.9959). The eight hand-built features already carried the signal that mattered — a real, working transfer-learning pipeline that also happens to be evidence this particular problem didn’t need one.</p>
</section>
<section id="why-a-random-split-would-have-been-a-lie" class="level2">
<h2 class="anchored" data-anchor-id="why-a-random-split-would-have-been-a-lie">Why a Random Split Would Have Been a Lie</h2>
<p>Because neighboring pixels always share a label, a random pixel-level train/test split would put a pixel in training and its immediate neighbor in test — that’s not generalization, it’s memorizing a map. I used a temporal holdout instead: train on the two earlier orbits, test on the later one, mirroring real deployment (score a future pass with a model trained on the past).</p>
<p>Then I went further. Rotating which of the three orbits gets held out (leave-one-orbit-out cross-validation — a follow-up analysis run after the report was submitted) shows what that single holdout number was hiding:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Held-out orbit</th>
<th>HGB-Base (8 feat.)</th>
<th>HGB-Full (40 feat.)</th>
<th>RF-Full (40 feat.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>O012791</td>
<td>0.8874</td>
<td>0.9088</td>
<td>0.7842</td>
</tr>
<tr class="even">
<td>O013257</td>
<td>0.9739</td>
<td>0.9840</td>
<td>0.9814</td>
</tr>
<tr class="odd">
<td>O013490</td>
<td><strong>0.9958</strong></td>
<td>0.9959</td>
<td>0.9861</td>
</tr>
</tbody>
</table>
<p>The headline 0.9958 is the <em>best</em> of three possible holdouts, not a stable property of the model. With only three orbit groups, there’s no averaging your way out of that spread — the honest error bar on this project is closer to ±0.05 AUC than the ±0.0003 seed-to-seed variance a naive robustness check would suggest.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<p>Every tree-based model cleared 0.98 AUC; every linear model fell over once handed all 40 features.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Features</th>
<th>ROC AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>RF (Base)</td>
<td>3</td>
<td>0.9944</td>
</tr>
<tr class="even">
<td><strong>HGB (Base) — selected</strong></td>
<td><strong>8</strong></td>
<td><strong>0.9958</strong></td>
</tr>
<tr class="odd">
<td>HGB (Full)</td>
<td>40</td>
<td>0.9959</td>
</tr>
<tr class="even">
<td>SVM (Full)</td>
<td>40</td>
<td>0.4148</td>
</tr>
<tr class="odd">
<td>Lasso Logistic (Full)</td>
<td>40</td>
<td>0.5109</td>
</tr>
</tbody>
</table>
<p>Three orders of magnitude of extra machinery (3 features → 40, RF → HGB) bought 0.0015 AUC. Handing the SVM the same 40 features it handled fine at 3 dropped it to 0.4148 — below chance — because margin-based models don’t shrug off collinearity the way trees do.</p>
<p>HGB-Base (8 features) was selected over HGB-Full (40 features, 0.0001 AUC better) because the better model needs a trained autoencoder and a patch-extraction pipeline running at inference time. That trade is an engineering decision, not a leaderboard result.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="spatial_errors.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Spatial map of HGB-Base classification errors on the temporal holdout. Errors cluster tightly at cloud-edge boundaries rather than scattering randomly across the image.</figcaption>
</figure>
</div>
<p>The confusion matrix is deliberately lopsided: 198 missed clouds against 3,017 false alarms (recall 0.9950, precision 0.9283) — a trade that fell out of class weighting, not a deliberate choice, but plausibly the right one for a downstream climate product where missing a cloud is costlier than a false alarm.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="permutation_importance.png" class="img-fluid figure-img" style="width:85.0%"></p>
<figcaption>Permutation importance for the selected model. SD dominates; the raw DF radiance — the camera angle the textbook NDAI index is built around — is measurably negative.</figcaption>
</figure>
</div>
<p>Two distinct failure modes fall out of the error analysis, both traceable to specific features rather than “the model got confused”: missed clouds run texture-masked (false negatives average SD = 1,376, nearly double the 706 of correctly caught clouds — the cloud’s own texture disappears into an already-heterogeneous surface), while false alarms are suspiciously smooth (false positives have a median CORR of 0.909 against 0.161 for true clouds — a clear-sky surface at the right angle can register almost identically across every camera, exactly what fools that feature).</p>
</section>
<section id="technologies-tools" class="level2">
<h2 class="anchored" data-anchor-id="technologies-tools">Technologies &amp; Tools</h2>
<p>Core stack: Python, PyTorch (autoencoder), scikit-learn (RF, HGB, SVM, logistic regression), pandas / NumPy</p>
<p>Feature engineering: AUC / KS / mutual-information separability ranking, angular-ratio sweep across all camera pairs, PCA on the radiance block</p>
<p>Model selection: temporal holdout + 5-fold stratified CV, leave-one-orbit-out cross-validation as a follow-up robustness check</p>
<p>Stability checks: label-noise robustness (5% training-label flip, 3 independent repetitions), unseen-orbit sanity checks on three fully unlabeled scenes</p>
</section>
<section id="links-resources" class="level2">
<h2 class="anchored" data-anchor-id="links-resources">Links &amp; Resources</h2>
<ul>
<li><a href="https://ricardo-pc.github.io/arctic-cloud-detection/">Interactive walkthrough</a>: the full analysis as an interactive site — play cloud detector against the real model, drag a live threshold across real feature histograms, and inspect any of 115,032 real pixels on a hoverable raster map showing raw radiances, engineered features, and the model’s prediction for that exact pixel</li>
<li><a href="https://github.com/ricardo-pc/stat-214/tree/main/lab2">GitHub Repository</a>: full codebase, feature engineering pipeline, and autoencoder training</li>
<li><a href="https://ricardo-pc.github.io/arctic-cloud-detection/report.pdf">Final Report (PDF)</a>: complete write-up with methodology and results</li>
</ul>
</section>
<section id="reflection" class="level2">
<h2 class="anchored" data-anchor-id="reflection">Reflection</h2>
<p>The most useful finding in this project isn’t in the leaderboard — it’s the discovery that the labeled test set structurally excludes the pixels the model finds hardest. Nobody asked me to check whether adjacent pixels ever disagreed on their label; I checked because it seemed like the kind of thing worth verifying before trusting any accuracy number downstream. It turned out to be the single most important caveat on the whole project, and it reframes what “0.9958 AUC” actually means: not “the model is almost never wrong,” but “the model is almost never wrong on the pixels we were confident enough to label.”</p>
<p>The leave-one-orbit-out analysis made the same point from a different angle. A single holdout number is a point estimate with an invisible error bar; rotating the holdout made that error bar visible, and it was much larger than the seed-to-seed variance anyone would normally report. Between the two, I came away convinced that for a project like this, the data-quality audit and the validation design matter more than which model wins the leaderboard — the model was the easy part.</p>
<hr>
<p><em>Completed August 2026 as a project for STAT 214: Data Analysis and Machine Learning for Real-World Decision Making at UC Berkeley.</em></p>


</section>

</main> <!-- /main -->
<script defer="" src="../../analytics.js?v=20260903-2"></script>
<div class="rpc-cheer-wrap">
<button class="rpc-cheer-launcher" id="rpc-cheer-launcher" type="button" aria-haspopup="dialog" aria-controls="rpc-cheer-dialog">
  <span class="rpc-cheer-launcher-icon" aria-hidden="true">♥</span>
  <span>Send a little boost</span>
</button>
</div>

<dialog class="rpc-cheer-dialog" id="rpc-cheer-dialog" aria-labelledby="rpc-cheer-title" aria-describedby="rpc-cheer-intro">
  <div class="rpc-cheer-panel">
    <button class="rpc-cheer-close" type="button" aria-label="Close boost station">×</button>

    <p class="rpc-cheer-eyebrow">Ricardo's boost station</p>
    <h2 id="rpc-cheer-title">Send love or send strength</h2>
    <p class="rpc-cheer-intro" id="rpc-cheer-intro">
      No note, name, or inbox needed. Pick what today calls for.
    </p>

    <div class="rpc-cheer-options">
      <button class="rpc-cheer-option rpc-cheer-love" type="button" data-cheer="love">
        <span class="rpc-cheer-option-icon" aria-hidden="true">♥</span>
        <span class="rpc-cheer-option-copy">
          <strong>Send love</strong>
          <small>“You are doing better than you think.”</small>
        </span>
      </button>
      <button class="rpc-cheer-option rpc-cheer-strength" type="button" data-cheer="strength">
        <span class="rpc-cheer-option-icon" aria-hidden="true">⚡</span>
        <span class="rpc-cheer-option-copy">
          <strong>Send strength</strong>
          <small>“Keep moving forward. You can do it.”</small>
        </span>
      </button>
    </div>

    <div class="rpc-cheer-receipt" aria-live="polite" aria-atomic="true">
      <p class="rpc-cheer-status" id="rpc-cheer-status">
        Send one—or both. A little encouragement goes a long way.
      </p>
      <div class="rpc-cheer-meter" aria-hidden="true">
        <span id="rpc-cheer-meter-fill"></span>
      </div>
      <p class="rpc-cheer-counts" id="rpc-cheer-counts">This visit: 0 love · 0 strength</p>
    </div>

    <div class="rpc-cheer-effects" aria-hidden="true"></div>
  </div>
</dialog>

<script defer="" src="../../cheers.js?v=20260903-2"></script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ricardo-pc\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Ricardo Pérez Castillo</p>
</div>   
    <div class="nav-footer-center">

<div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:ricardoperez@berkeley.edu">
      <i class="bi bi-envelope" role="img" aria-label="Email">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ricardo-pc">
      <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ricardoperezcastillo/">
      <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>